"""trade model changes

Revision ID: 0e6c87b0f322
Revises: a8283f106d90
Create Date: 2025-12-19 20:53:49.656491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e6c87b0f322'
down_revision: Union[str, Sequence[str], None] = 'a8283f106d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('instrument_name', sa.String(), nullable=True))
    op.add_column('trades', sa.Column('isin', sa.String(), nullable=True))
    op.add_column('trades', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('trades', sa.Column('operation_type', sa.String(), nullable=True))
    op.add_column('trades', sa.Column('sign', sa.String(), nullable=True))
    op.add_column('trades', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('exchange_rate', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('gross_amount', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('commission_fund', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('commission_bank', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('commission_sgr', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('commission_admin', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'commission_admin')
    op.drop_column('trades', 'commission_sgr')
    op.drop_column('trades', 'commission_bank')
    op.drop_column('trades', 'commission_fund')
    op.drop_column('trades', 'gross_amount')
    op.drop_column('trades', 'exchange_rate')
    op.drop_column('trades', 'quantity')
    op.drop_column('trades', 'sign')
    op.drop_column('trades', 'operation_type')
    op.drop_column('trades', 'currency')
    op.drop_column('trades', 'isin')
    op.drop_column('trades', 'instrument_name')
    # ### end Alembic commands ###
