"""add_leverage_and_margin_to_trades

Revision ID: 1a2b3c4d5e6f
Revises: c1a2b3d4e5f6
Create Date: 2026-04-13 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = 'c1a2b3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('leverage', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('percentage_margin', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'percentage_margin')
    op.drop_column('trades', 'leverage')
    # ### end Alembic commands ###
