// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_import_trades_api_trades_import_post
 */
export type BodyImportTradesApiTradesImportPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_login_api_login_post
 */
export type BodyLoginApiLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_upload_avatar_api_users__user_id__avatar_post
 */
export type BodyUploadAvatarApiUsersUserIdAvatarPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PasswordChange
 */
export type PasswordChange = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * ReportResponse
 */
export type ReportResponse = {
    /**
     * Total Profit
     */
    total_profit: number;
    /**
     * Total Loss
     */
    total_loss: number;
    /**
     * Win Probability
     */
    win_probability: number;
    /**
     * Loss Probability
     */
    loss_probability: number;
    /**
     * Avg Win
     */
    avg_win: number;
    /**
     * Avg Loss
     */
    avg_loss: number;
    /**
     * Expectancy
     */
    expectancy: number;
    /**
     * Capital
     */
    capital: number;
};

/**
 * RoleEnum
 */
export type RoleEnum = 'admin' | 'user';

/**
 * TokenSchema
 */
export type TokenSchema = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
    role: RoleEnum;
};

/**
 * TradeCreate
 */
export type TradeCreate = {
    /**
     * Date
     */
    date: string | null;
    /**
     * Pair
     */
    pair: string | null;
    /**
     * System
     */
    system: string | null;
    /**
     * Action
     */
    action: string | null;
    /**
     * Risk
     */
    risk: string | null;
    /**
     * Risk Percent
     */
    risk_percent: number | null;
    /**
     * Lots
     */
    lots: number | null;
    /**
     * Entry
     */
    entry: number | null;
    /**
     * Sl1 Pips
     */
    sl1_pips: number | null;
    /**
     * Tp1 Pips
     */
    tp1_pips: number | null;
    /**
     * Sl2 Pips
     */
    sl2_pips: number | null;
    /**
     * Tp2 Pips
     */
    tp2_pips: number | null;
    /**
     * Cancelled
     */
    cancelled: boolean | null;
    /**
     * Profit Or Loss
     */
    profit_or_loss: number | null;
    /**
     * Comments
     */
    comments: string | null;
};

/**
 * TradeResponse
 */
export type TradeResponse = {
    /**
     * Date
     */
    date: string | null;
    /**
     * Pair
     */
    pair: string | null;
    /**
     * System
     */
    system: string | null;
    /**
     * Action
     */
    action: string | null;
    /**
     * Risk
     */
    risk: string | null;
    /**
     * Risk Percent
     */
    risk_percent: number | null;
    /**
     * Lots
     */
    lots: number | null;
    /**
     * Entry
     */
    entry: number | null;
    /**
     * Sl1 Pips
     */
    sl1_pips: number | null;
    /**
     * Tp1 Pips
     */
    tp1_pips: number | null;
    /**
     * Sl2 Pips
     */
    sl2_pips: number | null;
    /**
     * Tp2 Pips
     */
    tp2_pips: number | null;
    /**
     * Cancelled
     */
    cancelled: boolean | null;
    /**
     * Profit Or Loss
     */
    profit_or_loss: number | null;
    /**
     * Comments
     */
    comments: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Owner Id
     */
    owner_id: number;
};

/**
 * TradeUpdate
 */
export type TradeUpdate = {
    /**
     * Symbol
     */
    symbol?: string | null;
    /**
     * Entry Price
     */
    entry_price?: number | null;
    /**
     * Exit Price
     */
    exit_price?: number | null;
    /**
     * Quantity
     */
    quantity?: number | null;
    /**
     * Position Type
     */
    position_type?: string | null;
    /**
     * Profit Or Loss
     */
    profit_or_loss?: number | null;
    /**
     * Cancelled
     */
    cancelled?: boolean | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    role?: RoleEnum;
    /**
     * Initial Capital
     */
    initial_capital?: number;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    role: RoleEnum;
    /**
     * Valid
     */
    valid: boolean;
    /**
     * Initial Capital
     */
    initial_capital: number;
    /**
     * Avatar
     */
    avatar: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Username
     */
    username?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Role
     */
    role?: string | null;
    /**
     * Initial Capital
     */
    initial_capital?: number | null;
    /**
     * Valid
     */
    valid?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ImportTradesApiTradesImportPostData = {
    body: BodyImportTradesApiTradesImportPost;
    path?: never;
    query?: never;
    url: '/api/trades/import';
};

export type ImportTradesApiTradesImportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportTradesApiTradesImportPostError = ImportTradesApiTradesImportPostErrors[keyof ImportTradesApiTradesImportPostErrors];

export type ImportTradesApiTradesImportPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAvatarApiUsersUserIdAvatarGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/{user_id}/avatar';
};

export type GetAvatarApiUsersUserIdAvatarGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadAvatarApiUsersUserIdAvatarPostData = {
    body: BodyUploadAvatarApiUsersUserIdAvatarPost;
    path?: never;
    query?: never;
    url: '/api/users/{user_id}/avatar';
};

export type UploadAvatarApiUsersUserIdAvatarPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadAvatarApiUsersUserIdAvatarPostError = UploadAvatarApiUsersUserIdAvatarPostErrors[keyof UploadAvatarApiUsersUserIdAvatarPostErrors];

export type UploadAvatarApiUsersUserIdAvatarPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AskQuestionApiAiAskPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Question
         */
        question: string;
        /**
         * User Data Required
         */
        user_data_required?: boolean;
    };
    url: '/api/ai/ask';
};

export type AskQuestionApiAiAskPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AskQuestionApiAiAskPostError = AskQuestionApiAiAskPostErrors[keyof AskQuestionApiAiAskPostErrors];

export type AskQuestionApiAiAskPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUsersApiUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type GetUsersApiUsersGetResponses = {
    /**
     * Response Get Users Api Users  Get
     *
     * Successful Response
     */
    200: Array<UserResponse>;
};

export type GetUsersApiUsersGetResponse = GetUsersApiUsersGetResponses[keyof GetUsersApiUsersGetResponses];

export type CreateUserApiUsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type CreateUserApiUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiUsersPostError = CreateUserApiUsersPostErrors[keyof CreateUserApiUsersPostErrors];

export type CreateUserApiUsersPostResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type CreateUserApiUsersPostResponse = CreateUserApiUsersPostResponses[keyof CreateUserApiUsersPostResponses];

export type ReadUsersMeApiUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type ReadUsersMeApiUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type ReadUsersMeApiUsersMeGetResponse = ReadUsersMeApiUsersMeGetResponses[keyof ReadUsersMeApiUsersMeGetResponses];

export type DeleteUserApiUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type DeleteUserApiUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserApiUsersUserIdDeleteError = DeleteUserApiUsersUserIdDeleteErrors[keyof DeleteUserApiUsersUserIdDeleteErrors];

export type DeleteUserApiUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUserApiUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type GetUserApiUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserApiUsersUserIdGetError = GetUserApiUsersUserIdGetErrors[keyof GetUserApiUsersUserIdGetErrors];

export type GetUserApiUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetUserApiUsersUserIdGetResponse = GetUserApiUsersUserIdGetResponses[keyof GetUserApiUsersUserIdGetResponses];

export type UpdateUserApiUsersUserIdPutData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type UpdateUserApiUsersUserIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserApiUsersUserIdPutError = UpdateUserApiUsersUserIdPutErrors[keyof UpdateUserApiUsersUserIdPutErrors];

export type UpdateUserApiUsersUserIdPutResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type UpdateUserApiUsersUserIdPutResponse = UpdateUserApiUsersUserIdPutResponses[keyof UpdateUserApiUsersUserIdPutResponses];

export type ChangeOwnPasswordApiUsersMeChangePasswordPostData = {
    body: PasswordChange;
    path?: never;
    query?: never;
    url: '/api/users/me/change-password';
};

export type ChangeOwnPasswordApiUsersMeChangePasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangeOwnPasswordApiUsersMeChangePasswordPostError = ChangeOwnPasswordApiUsersMeChangePasswordPostErrors[keyof ChangeOwnPasswordApiUsersMeChangePasswordPostErrors];

export type ChangeOwnPasswordApiUsersMeChangePasswordPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChangeUserPasswordApiUsersUserIdChangePasswordPostData = {
    body: PasswordChange;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}/change-password';
};

export type ChangeUserPasswordApiUsersUserIdChangePasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangeUserPasswordApiUsersUserIdChangePasswordPostError = ChangeUserPasswordApiUsersUserIdChangePasswordPostErrors[keyof ChangeUserPasswordApiUsersUserIdChangePasswordPostErrors];

export type ChangeUserPasswordApiUsersUserIdChangePasswordPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginApiLoginPostData = {
    body: BodyLoginApiLoginPost;
    path?: never;
    query?: never;
    url: '/api/login';
};

export type LoginApiLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiLoginPostError = LoginApiLoginPostErrors[keyof LoginApiLoginPostErrors];

export type LoginApiLoginPostResponses = {
    /**
     * Successful Response
     */
    200: TokenSchema;
};

export type LoginApiLoginPostResponse = LoginApiLoginPostResponses[keyof LoginApiLoginPostResponses];

export type DeleteTradesApiTradesDeleteData = {
    /**
     * Trade Ids
     */
    body: Array<number>;
    path?: never;
    query?: never;
    url: '/api/trades/';
};

export type DeleteTradesApiTradesDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTradesApiTradesDeleteError = DeleteTradesApiTradesDeleteErrors[keyof DeleteTradesApiTradesDeleteErrors];

export type DeleteTradesApiTradesDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListTradesApiTradesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/trades/';
};

export type ListTradesApiTradesGetResponses = {
    /**
     * Response List Trades Api Trades  Get
     *
     * Successful Response
     */
    200: Array<TradeResponse>;
};

export type ListTradesApiTradesGetResponse = ListTradesApiTradesGetResponses[keyof ListTradesApiTradesGetResponses];

export type CreateTradeApiTradesPostData = {
    body: TradeCreate;
    path?: never;
    query?: never;
    url: '/api/trades/';
};

export type CreateTradeApiTradesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTradeApiTradesPostError = CreateTradeApiTradesPostErrors[keyof CreateTradeApiTradesPostErrors];

export type CreateTradeApiTradesPostResponses = {
    /**
     * Successful Response
     */
    200: TradeResponse;
};

export type CreateTradeApiTradesPostResponse = CreateTradeApiTradesPostResponses[keyof CreateTradeApiTradesPostResponses];

export type DeleteTradeApiTradesTradeIdDeleteData = {
    body?: never;
    path: {
        /**
         * Trade Id
         */
        trade_id: number;
    };
    query?: never;
    url: '/api/trades/{trade_id}';
};

export type DeleteTradeApiTradesTradeIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTradeApiTradesTradeIdDeleteError = DeleteTradeApiTradesTradeIdDeleteErrors[keyof DeleteTradeApiTradesTradeIdDeleteErrors];

export type DeleteTradeApiTradesTradeIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTradeApiTradesTradeIdGetData = {
    body?: never;
    path: {
        /**
         * Trade Id
         */
        trade_id: number;
    };
    query?: never;
    url: '/api/trades/{trade_id}';
};

export type GetTradeApiTradesTradeIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTradeApiTradesTradeIdGetError = GetTradeApiTradesTradeIdGetErrors[keyof GetTradeApiTradesTradeIdGetErrors];

export type GetTradeApiTradesTradeIdGetResponses = {
    /**
     * Successful Response
     */
    200: TradeResponse;
};

export type GetTradeApiTradesTradeIdGetResponse = GetTradeApiTradesTradeIdGetResponses[keyof GetTradeApiTradesTradeIdGetResponses];

export type UpdateTradeApiTradesTradeIdPutData = {
    body: TradeUpdate;
    path: {
        /**
         * Trade Id
         */
        trade_id: number;
    };
    query?: never;
    url: '/api/trades/{trade_id}';
};

export type UpdateTradeApiTradesTradeIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTradeApiTradesTradeIdPutError = UpdateTradeApiTradesTradeIdPutErrors[keyof UpdateTradeApiTradesTradeIdPutErrors];

export type UpdateTradeApiTradesTradeIdPutResponses = {
    /**
     * Successful Response
     */
    200: TradeResponse;
};

export type UpdateTradeApiTradesTradeIdPutResponse = UpdateTradeApiTradesTradeIdPutResponses[keyof UpdateTradeApiTradesTradeIdPutResponses];

export type CancelTradeApiTradesTradeIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Trade Id
         */
        trade_id: number;
    };
    query?: never;
    url: '/api/trades/{trade_id}/cancel';
};

export type CancelTradeApiTradesTradeIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelTradeApiTradesTradeIdCancelPostError = CancelTradeApiTradesTradeIdCancelPostErrors[keyof CancelTradeApiTradesTradeIdCancelPostErrors];

export type CancelTradeApiTradesTradeIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetReportApiReportGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/report/';
};

export type GetReportApiReportGetResponses = {
    /**
     * Successful Response
     */
    200: ReportResponse;
};

export type GetReportApiReportGetResponse = GetReportApiReportGetResponses[keyof GetReportApiReportGetResponses];

export type HealthCheckApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthCheckApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootApiGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/';
};

export type RootApiGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
