// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AnalysisCreate
 */
export type AnalysisCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Pair
     */
    pair?: string | null;
    /**
     * Timeframe
     */
    timeframe?: string | null;
    /**
     * Content
     */
    content?: string;
};

/**
 * AnalysisResponse
 */
export type AnalysisResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Pair
     */
    pair?: string | null;
    /**
     * Timeframe
     */
    timeframe?: string | null;
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Owner Id
     */
    owner_id: number;
};

/**
 * AnalysisResponseWithShares
 */
export type AnalysisResponseWithShares = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Pair
     */
    pair?: string | null;
    /**
     * Timeframe
     */
    timeframe?: string | null;
    /**
     * Content
     */
    content: string;
    /**
     * Pinned
     */
    pinned: boolean;
    /**
     * Pin Order
     */
    pin_order: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Owner Id
     */
    owner_id: number;
    /**
     * Is Shared
     */
    is_shared?: boolean;
    shared_by_user?: UserBasicResponse | null;
    /**
     * Shares
     */
    shares?: Array<AnalysisShareResponse>;
};

/**
 * AnalysisShareResponse
 */
export type AnalysisShareResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Analysis Id
     */
    analysis_id: number;
    /**
     * Shared With User Id
     */
    shared_with_user_id: number;
    /**
     * Shared By User Id
     */
    shared_by_user_id: number;
    /**
     * Created At
     */
    created_at: string;
    shared_by_user: UserBasicResponse;
    shared_with_user: UserBasicResponse;
};

/**
 * AnalysisUpdate
 */
export type AnalysisUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Pair
     */
    pair?: string | null;
    /**
     * Timeframe
     */
    timeframe?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Pinned
     */
    pinned?: boolean | null;
    /**
     * Pin Order
     */
    pin_order?: number | null;
};

/**
 * Body_import_trades_api_trades_import_post
 */
export type BodyImportTradesApiTradesImportPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_login_api_login_post
 */
export type BodyLoginApiLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_upload_analysis_image_api_analyses_images_upload_post
 */
export type BodyUploadAnalysisImageApiAnalysesImagesUploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_avatar_api_users__user_id__avatar_post
 */
export type BodyUploadAvatarApiUsersUserIdAvatarPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * FavoriteBookmarkCreate
 */
export type FavoriteBookmarkCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Url
     */
    url: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Color
     */
    color?: string;
    /**
     * Emoji
     */
    emoji?: string;
};

/**
 * FavoriteBookmarkResponse
 */
export type FavoriteBookmarkResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Url
     */
    url: string;
    /**
     * Description
     */
    description: string;
    /**
     * Color
     */
    color: string;
    /**
     * Emoji
     */
    emoji: string;
    /**
     * Sort Order
     */
    sort_order: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Owner Id
     */
    owner_id: number;
};

/**
 * FavoriteBookmarkUpdate
 */
export type FavoriteBookmarkUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Url
     */
    url?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Color
     */
    color?: string | null;
    /**
     * Emoji
     */
    emoji?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PasswordChange
 */
export type PasswordChange = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * ReadLaterBookmarkCreate
 */
export type ReadLaterBookmarkCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Summary
     */
    summary?: string;
    /**
     * Url
     */
    url: string;
    /**
     * Published At
     */
    published_at?: string | null;
    /**
     * Source
     */
    source?: string;
    /**
     * Source Id
     */
    source_id?: string;
    /**
     * Source Color
     */
    source_color?: string;
    /**
     * Site Url
     */
    site_url?: string;
    /**
     * Expires Days
     */
    expires_days?: number | null;
};

/**
 * ReadLaterBookmarkResponse
 */
export type ReadLaterBookmarkResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Summary
     */
    summary: string;
    /**
     * Url
     */
    url: string;
    /**
     * Published At
     */
    published_at: string | null;
    /**
     * Source
     */
    source: string;
    /**
     * Source Id
     */
    source_id: string;
    /**
     * Source Color
     */
    source_color: string;
    /**
     * Site Url
     */
    site_url: string;
    /**
     * Saved At
     */
    saved_at: string;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Pinned
     */
    pinned: boolean;
    /**
     * Pin Order
     */
    pin_order: number;
    /**
     * Owner Id
     */
    owner_id: number;
};

/**
 * ReadLaterExpiryUpdate
 */
export type ReadLaterExpiryUpdate = {
    /**
     * Expires Days
     */
    expires_days?: number | null;
};

/**
 * ReadLaterReorderRequest
 */
export type ReadLaterReorderRequest = {
    /**
     * Order
     */
    order: Array<number>;
};

/**
 * ReorderRequest
 */
export type ReorderRequest = {
    /**
     * Order
     */
    order: Array<number>;
};

/**
 * ReportResponse
 */
export type ReportResponse = {
    /**
     * Total Profit
     */
    total_profit: number;
    /**
     * Total Loss
     */
    total_loss: number;
    /**
     * Win Probability
     */
    win_probability: number;
    /**
     * Loss Probability
     */
    loss_probability: number;
    /**
     * Avg Win
     */
    avg_win: number;
    /**
     * Avg Loss
     */
    avg_loss: number;
    /**
     * Expectancy
     */
    expectancy: number;
    /**
     * Capital
     */
    capital: number;
    /**
     * Account Currency
     */
    account_currency?: string;
    /**
     * Total Pnl
     */
    total_pnl?: number;
    /**
     * Num Trades
     */
    num_trades?: number;
};

/**
 * RoleEnum
 */
export type RoleEnum = 'admin' | 'user';

/**
 * ShareAnalysisRequest
 */
export type ShareAnalysisRequest = {
    /**
     * User Ids
     */
    user_ids: Array<number>;
};

/**
 * TokenSchema
 */
export type TokenSchema = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
    role: RoleEnum;
};

/**
 * TradeCreate
 */
export type TradeCreate = {
    /**
     * Date
     */
    date: string | null;
    /**
     * Pair
     */
    pair?: string | null;
    /**
     * System
     */
    system?: string | null;
    /**
     * Action
     */
    action?: string | null;
    /**
     * Risk
     */
    risk?: string | null;
    /**
     * Risk Percent
     */
    risk_percent?: number | null;
    /**
     * Lots
     */
    lots?: number | null;
    /**
     * Entry
     */
    entry?: number | null;
    /**
     * Sl1 Pips
     */
    sl1_pips?: number | null;
    /**
     * Tp1 Pips
     */
    tp1_pips?: number | null;
    /**
     * Sl2 Pips
     */
    sl2_pips?: number | null;
    /**
     * Tp2 Pips
     */
    tp2_pips?: number | null;
    /**
     * Cancelled
     */
    cancelled?: boolean | null;
    /**
     * Profit Or Loss
     */
    profit_or_loss?: number | null;
    /**
     * Comments
     */
    comments?: string | null;
    /**
     * Instrument Name
     */
    instrument_name?: string | null;
    /**
     * Isin
     */
    isin?: string | null;
    /**
     * Currency
     */
    currency?: string | null;
    /**
     * Operation Type
     */
    operation_type?: string | null;
    /**
     * Sign
     */
    sign?: string | null;
    /**
     * Quantity
     */
    quantity?: number | null;
    /**
     * Exchange Rate
     */
    exchange_rate?: number | null;
    /**
     * Gross Amount
     */
    gross_amount?: number | null;
    /**
     * Commission Fund
     */
    commission_fund?: number | null;
    /**
     * Commission Bank
     */
    commission_bank?: number | null;
    /**
     * Commission Sgr
     */
    commission_sgr?: number | null;
    /**
     * Commission Admin
     */
    commission_admin?: number | null;
    /**
     * Leverage
     */
    leverage?: number | null;
    /**
     * Percentage Margin
     */
    percentage_margin?: number | null;
};

/**
 * TradeResponse
 */
export type TradeResponse = {
    /**
     * Date
     */
    date: string | null;
    /**
     * Pair
     */
    pair?: string | null;
    /**
     * System
     */
    system?: string | null;
    /**
     * Action
     */
    action?: string | null;
    /**
     * Risk
     */
    risk?: string | null;
    /**
     * Risk Percent
     */
    risk_percent?: number | null;
    /**
     * Lots
     */
    lots?: number | null;
    /**
     * Entry
     */
    entry?: number | null;
    /**
     * Sl1 Pips
     */
    sl1_pips?: number | null;
    /**
     * Tp1 Pips
     */
    tp1_pips?: number | null;
    /**
     * Sl2 Pips
     */
    sl2_pips?: number | null;
    /**
     * Tp2 Pips
     */
    tp2_pips?: number | null;
    /**
     * Cancelled
     */
    cancelled?: boolean | null;
    /**
     * Profit Or Loss
     */
    profit_or_loss?: number | null;
    /**
     * Comments
     */
    comments?: string | null;
    /**
     * Instrument Name
     */
    instrument_name?: string | null;
    /**
     * Isin
     */
    isin?: string | null;
    /**
     * Currency
     */
    currency?: string | null;
    /**
     * Operation Type
     */
    operation_type?: string | null;
    /**
     * Sign
     */
    sign?: string | null;
    /**
     * Quantity
     */
    quantity?: number | null;
    /**
     * Exchange Rate
     */
    exchange_rate?: number | null;
    /**
     * Gross Amount
     */
    gross_amount?: number | null;
    /**
     * Commission Fund
     */
    commission_fund?: number | null;
    /**
     * Commission Bank
     */
    commission_bank?: number | null;
    /**
     * Commission Sgr
     */
    commission_sgr?: number | null;
    /**
     * Commission Admin
     */
    commission_admin?: number | null;
    /**
     * Leverage
     */
    leverage?: number | null;
    /**
     * Percentage Margin
     */
    percentage_margin?: number | null;
    /**
     * Id
     */
    id: number;
    /**
     * Owner Id
     */
    owner_id: number;
};

/**
 * TradeUpdate
 */
export type TradeUpdate = {
    /**
     * Date
     */
    date: string | null;
    /**
     * Pair
     */
    pair?: string | null;
    /**
     * System
     */
    system?: string | null;
    /**
     * Action
     */
    action?: string | null;
    /**
     * Risk
     */
    risk?: string | null;
    /**
     * Risk Percent
     */
    risk_percent?: number | null;
    /**
     * Lots
     */
    lots?: number | null;
    /**
     * Entry
     */
    entry?: number | null;
    /**
     * Sl1 Pips
     */
    sl1_pips?: number | null;
    /**
     * Tp1 Pips
     */
    tp1_pips?: number | null;
    /**
     * Sl2 Pips
     */
    sl2_pips?: number | null;
    /**
     * Tp2 Pips
     */
    tp2_pips?: number | null;
    /**
     * Cancelled
     */
    cancelled?: boolean | null;
    /**
     * Profit Or Loss
     */
    profit_or_loss?: number | null;
    /**
     * Comments
     */
    comments?: string | null;
    /**
     * Instrument Name
     */
    instrument_name?: string | null;
    /**
     * Isin
     */
    isin?: string | null;
    /**
     * Currency
     */
    currency?: string | null;
    /**
     * Operation Type
     */
    operation_type?: string | null;
    /**
     * Sign
     */
    sign?: string | null;
    /**
     * Quantity
     */
    quantity?: number | null;
    /**
     * Exchange Rate
     */
    exchange_rate?: number | null;
    /**
     * Gross Amount
     */
    gross_amount?: number | null;
    /**
     * Commission Fund
     */
    commission_fund?: number | null;
    /**
     * Commission Bank
     */
    commission_bank?: number | null;
    /**
     * Commission Sgr
     */
    commission_sgr?: number | null;
    /**
     * Commission Admin
     */
    commission_admin?: number | null;
    /**
     * Leverage
     */
    leverage?: number | null;
    /**
     * Percentage Margin
     */
    percentage_margin?: number | null;
};

/**
 * UserBasicResponse
 */
export type UserBasicResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Avatar
     */
    avatar: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    role?: RoleEnum;
    /**
     * Initial Capital
     */
    initial_capital?: number;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    role: RoleEnum;
    /**
     * Valid
     */
    valid: boolean;
    /**
     * Initial Capital
     */
    initial_capital: number;
    /**
     * Account Currency
     */
    account_currency?: string;
    /**
     * Avatar
     */
    avatar: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Username
     */
    username?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Role
     */
    role?: string | null;
    /**
     * Initial Capital
     */
    initial_capital?: number | null;
    /**
     * Account Currency
     */
    account_currency?: string | null;
    /**
     * Valid
     */
    valid?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ImportTradesApiTradesImportPostData = {
    body: BodyImportTradesApiTradesImportPost;
    path?: never;
    query?: never;
    url: '/api/trades/import';
};

export type ImportTradesApiTradesImportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportTradesApiTradesImportPostError = ImportTradesApiTradesImportPostErrors[keyof ImportTradesApiTradesImportPostErrors];

export type ImportTradesApiTradesImportPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAvatarApiUsersUserIdAvatarGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/{user_id}/avatar';
};

export type GetAvatarApiUsersUserIdAvatarGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadAvatarApiUsersUserIdAvatarPostData = {
    body: BodyUploadAvatarApiUsersUserIdAvatarPost;
    path?: never;
    query?: never;
    url: '/api/users/{user_id}/avatar';
};

export type UploadAvatarApiUsersUserIdAvatarPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadAvatarApiUsersUserIdAvatarPostError = UploadAvatarApiUsersUserIdAvatarPostErrors[keyof UploadAvatarApiUsersUserIdAvatarPostErrors];

export type UploadAvatarApiUsersUserIdAvatarPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AskQuestionApiAiAskPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Question
         */
        question: string;
        /**
         * User Data Required
         */
        user_data_required?: boolean;
    };
    url: '/api/ai/ask';
};

export type AskQuestionApiAiAskPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AskQuestionApiAiAskPostError = AskQuestionApiAiAskPostErrors[keyof AskQuestionApiAiAskPostErrors];

export type AskQuestionApiAiAskPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUsersApiUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type GetUsersApiUsersGetResponses = {
    /**
     * Response Get Users Api Users  Get
     *
     * Successful Response
     */
    200: Array<UserResponse>;
};

export type GetUsersApiUsersGetResponse = GetUsersApiUsersGetResponses[keyof GetUsersApiUsersGetResponses];

export type CreateUserApiUsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type CreateUserApiUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiUsersPostError = CreateUserApiUsersPostErrors[keyof CreateUserApiUsersPostErrors];

export type CreateUserApiUsersPostResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type CreateUserApiUsersPostResponse = CreateUserApiUsersPostResponses[keyof CreateUserApiUsersPostResponses];

export type ReadUsersMeApiUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type ReadUsersMeApiUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type ReadUsersMeApiUsersMeGetResponse = ReadUsersMeApiUsersMeGetResponses[keyof ReadUsersMeApiUsersMeGetResponses];

export type UpdateCurrentUserApiUsersMePutData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type UpdateCurrentUserApiUsersMePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCurrentUserApiUsersMePutError = UpdateCurrentUserApiUsersMePutErrors[keyof UpdateCurrentUserApiUsersMePutErrors];

export type UpdateCurrentUserApiUsersMePutResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type UpdateCurrentUserApiUsersMePutResponse = UpdateCurrentUserApiUsersMePutResponses[keyof UpdateCurrentUserApiUsersMePutResponses];

export type DeleteUserApiUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type DeleteUserApiUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserApiUsersUserIdDeleteError = DeleteUserApiUsersUserIdDeleteErrors[keyof DeleteUserApiUsersUserIdDeleteErrors];

export type DeleteUserApiUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUserApiUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type GetUserApiUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserApiUsersUserIdGetError = GetUserApiUsersUserIdGetErrors[keyof GetUserApiUsersUserIdGetErrors];

export type GetUserApiUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetUserApiUsersUserIdGetResponse = GetUserApiUsersUserIdGetResponses[keyof GetUserApiUsersUserIdGetResponses];

export type UpdateUserApiUsersUserIdPutData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type UpdateUserApiUsersUserIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserApiUsersUserIdPutError = UpdateUserApiUsersUserIdPutErrors[keyof UpdateUserApiUsersUserIdPutErrors];

export type UpdateUserApiUsersUserIdPutResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type UpdateUserApiUsersUserIdPutResponse = UpdateUserApiUsersUserIdPutResponses[keyof UpdateUserApiUsersUserIdPutResponses];

export type ChangeOwnPasswordApiUsersMeChangePasswordPostData = {
    body: PasswordChange;
    path?: never;
    query?: never;
    url: '/api/users/me/change-password';
};

export type ChangeOwnPasswordApiUsersMeChangePasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangeOwnPasswordApiUsersMeChangePasswordPostError = ChangeOwnPasswordApiUsersMeChangePasswordPostErrors[keyof ChangeOwnPasswordApiUsersMeChangePasswordPostErrors];

export type ChangeOwnPasswordApiUsersMeChangePasswordPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChangeUserPasswordApiUsersUserIdChangePasswordPostData = {
    body: PasswordChange;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/users/{user_id}/change-password';
};

export type ChangeUserPasswordApiUsersUserIdChangePasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangeUserPasswordApiUsersUserIdChangePasswordPostError = ChangeUserPasswordApiUsersUserIdChangePasswordPostErrors[keyof ChangeUserPasswordApiUsersUserIdChangePasswordPostErrors];

export type ChangeUserPasswordApiUsersUserIdChangePasswordPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginApiLoginPostData = {
    body: BodyLoginApiLoginPost;
    path?: never;
    query?: never;
    url: '/api/login';
};

export type LoginApiLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiLoginPostError = LoginApiLoginPostErrors[keyof LoginApiLoginPostErrors];

export type LoginApiLoginPostResponses = {
    /**
     * Successful Response
     */
    200: TokenSchema;
};

export type LoginApiLoginPostResponse = LoginApiLoginPostResponses[keyof LoginApiLoginPostResponses];

export type DeleteTradesApiTradesDeleteData = {
    /**
     * Trade Ids
     */
    body: Array<number>;
    path?: never;
    query?: never;
    url: '/api/trades/';
};

export type DeleteTradesApiTradesDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTradesApiTradesDeleteError = DeleteTradesApiTradesDeleteErrors[keyof DeleteTradesApiTradesDeleteErrors];

export type DeleteTradesApiTradesDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListTradesApiTradesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/trades/';
};

export type ListTradesApiTradesGetResponses = {
    /**
     * Response List Trades Api Trades  Get
     *
     * Successful Response
     */
    200: Array<TradeResponse>;
};

export type ListTradesApiTradesGetResponse = ListTradesApiTradesGetResponses[keyof ListTradesApiTradesGetResponses];

export type CreateTradeApiTradesPostData = {
    body: TradeCreate;
    path?: never;
    query?: never;
    url: '/api/trades/';
};

export type CreateTradeApiTradesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTradeApiTradesPostError = CreateTradeApiTradesPostErrors[keyof CreateTradeApiTradesPostErrors];

export type CreateTradeApiTradesPostResponses = {
    /**
     * Successful Response
     */
    200: TradeResponse;
};

export type CreateTradeApiTradesPostResponse = CreateTradeApiTradesPostResponses[keyof CreateTradeApiTradesPostResponses];

export type DeleteTradeApiTradesTradeIdDeleteData = {
    body?: never;
    path: {
        /**
         * Trade Id
         */
        trade_id: number;
    };
    query?: never;
    url: '/api/trades/{trade_id}';
};

export type DeleteTradeApiTradesTradeIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTradeApiTradesTradeIdDeleteError = DeleteTradeApiTradesTradeIdDeleteErrors[keyof DeleteTradeApiTradesTradeIdDeleteErrors];

export type DeleteTradeApiTradesTradeIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTradeApiTradesTradeIdGetData = {
    body?: never;
    path: {
        /**
         * Trade Id
         */
        trade_id: number;
    };
    query?: never;
    url: '/api/trades/{trade_id}';
};

export type GetTradeApiTradesTradeIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTradeApiTradesTradeIdGetError = GetTradeApiTradesTradeIdGetErrors[keyof GetTradeApiTradesTradeIdGetErrors];

export type GetTradeApiTradesTradeIdGetResponses = {
    /**
     * Successful Response
     */
    200: TradeResponse;
};

export type GetTradeApiTradesTradeIdGetResponse = GetTradeApiTradesTradeIdGetResponses[keyof GetTradeApiTradesTradeIdGetResponses];

export type UpdateTradeApiTradesTradeIdPutData = {
    body: TradeUpdate;
    path: {
        /**
         * Trade Id
         */
        trade_id: number;
    };
    query?: never;
    url: '/api/trades/{trade_id}';
};

export type UpdateTradeApiTradesTradeIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTradeApiTradesTradeIdPutError = UpdateTradeApiTradesTradeIdPutErrors[keyof UpdateTradeApiTradesTradeIdPutErrors];

export type UpdateTradeApiTradesTradeIdPutResponses = {
    /**
     * Successful Response
     */
    200: TradeResponse;
};

export type UpdateTradeApiTradesTradeIdPutResponse = UpdateTradeApiTradesTradeIdPutResponses[keyof UpdateTradeApiTradesTradeIdPutResponses];

export type CancelTradeApiTradesTradeIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Trade Id
         */
        trade_id: number;
    };
    query?: never;
    url: '/api/trades/{trade_id}/cancel';
};

export type CancelTradeApiTradesTradeIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelTradeApiTradesTradeIdCancelPostError = CancelTradeApiTradesTradeIdCancelPostErrors[keyof CancelTradeApiTradesTradeIdCancelPostErrors];

export type CancelTradeApiTradesTradeIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetReportApiReportGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/report/';
};

export type GetReportApiReportGetResponses = {
    /**
     * Successful Response
     */
    200: ReportResponse;
};

export type GetReportApiReportGetResponse = GetReportApiReportGetResponses[keyof GetReportApiReportGetResponses];

export type GetPositionsByCurrencyApiReportPositionsByCurrencyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/report/positions-by-currency';
};

export type GetPositionsByCurrencyApiReportPositionsByCurrencyGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetExchangeRatesApiExchangeRatesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * From Currency
         */
        from_currency?: string;
        /**
         * To Currency
         */
        to_currency?: string;
    };
    url: '/api/exchange-rates';
};

export type GetExchangeRatesApiExchangeRatesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetExchangeRatesApiExchangeRatesGetError = GetExchangeRatesApiExchangeRatesGetErrors[keyof GetExchangeRatesApiExchangeRatesGetErrors];

export type GetExchangeRatesApiExchangeRatesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllExchangeRatesApiExchangeRatesAllGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Base Currency
         */
        base_currency?: string;
    };
    url: '/api/exchange-rates/all';
};

export type GetAllExchangeRatesApiExchangeRatesAllGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllExchangeRatesApiExchangeRatesAllGetError = GetAllExchangeRatesApiExchangeRatesAllGetErrors[keyof GetAllExchangeRatesApiExchangeRatesAllGetErrors];

export type GetAllExchangeRatesApiExchangeRatesAllGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthCheckApiHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootApiGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/';
};

export type RootApiGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadAnalysisImageApiAnalysesImagesUploadPostData = {
    body: BodyUploadAnalysisImageApiAnalysesImagesUploadPost;
    path?: never;
    query?: never;
    url: '/api/analyses/images/upload';
};

export type UploadAnalysisImageApiAnalysesImagesUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadAnalysisImageApiAnalysesImagesUploadPostError = UploadAnalysisImageApiAnalysesImagesUploadPostErrors[keyof UploadAnalysisImageApiAnalysesImagesUploadPostErrors];

export type UploadAnalysisImageApiAnalysesImagesUploadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListAnalysesApiAnalysesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/analyses/';
};

export type ListAnalysesApiAnalysesGetResponses = {
    /**
     * Response List Analyses Api Analyses  Get
     *
     * Successful Response
     */
    200: Array<AnalysisResponseWithShares>;
};

export type ListAnalysesApiAnalysesGetResponse = ListAnalysesApiAnalysesGetResponses[keyof ListAnalysesApiAnalysesGetResponses];

export type CreateAnalysisApiAnalysesPostData = {
    body: AnalysisCreate;
    path?: never;
    query?: never;
    url: '/api/analyses/';
};

export type CreateAnalysisApiAnalysesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAnalysisApiAnalysesPostError = CreateAnalysisApiAnalysesPostErrors[keyof CreateAnalysisApiAnalysesPostErrors];

export type CreateAnalysisApiAnalysesPostResponses = {
    /**
     * Successful Response
     */
    200: AnalysisResponse;
};

export type CreateAnalysisApiAnalysesPostResponse = CreateAnalysisApiAnalysesPostResponses[keyof CreateAnalysisApiAnalysesPostResponses];

export type DeleteAnalysisApiAnalysesAnalysisIdDeleteData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: number;
    };
    query?: never;
    url: '/api/analyses/{analysis_id}';
};

export type DeleteAnalysisApiAnalysesAnalysisIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAnalysisApiAnalysesAnalysisIdDeleteError = DeleteAnalysisApiAnalysesAnalysisIdDeleteErrors[keyof DeleteAnalysisApiAnalysesAnalysisIdDeleteErrors];

export type DeleteAnalysisApiAnalysesAnalysisIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAnalysisApiAnalysesAnalysisIdGetData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: number;
    };
    query?: never;
    url: '/api/analyses/{analysis_id}';
};

export type GetAnalysisApiAnalysesAnalysisIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAnalysisApiAnalysesAnalysisIdGetError = GetAnalysisApiAnalysesAnalysisIdGetErrors[keyof GetAnalysisApiAnalysesAnalysisIdGetErrors];

export type GetAnalysisApiAnalysesAnalysisIdGetResponses = {
    /**
     * Successful Response
     */
    200: AnalysisResponseWithShares;
};

export type GetAnalysisApiAnalysesAnalysisIdGetResponse = GetAnalysisApiAnalysesAnalysisIdGetResponses[keyof GetAnalysisApiAnalysesAnalysisIdGetResponses];

export type UpdateAnalysisApiAnalysesAnalysisIdPutData = {
    body: AnalysisUpdate;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: number;
    };
    query?: never;
    url: '/api/analyses/{analysis_id}';
};

export type UpdateAnalysisApiAnalysesAnalysisIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAnalysisApiAnalysesAnalysisIdPutError = UpdateAnalysisApiAnalysesAnalysisIdPutErrors[keyof UpdateAnalysisApiAnalysesAnalysisIdPutErrors];

export type UpdateAnalysisApiAnalysesAnalysisIdPutResponses = {
    /**
     * Successful Response
     */
    200: AnalysisResponse;
};

export type UpdateAnalysisApiAnalysesAnalysisIdPutResponse = UpdateAnalysisApiAnalysesAnalysisIdPutResponses[keyof UpdateAnalysisApiAnalysesAnalysisIdPutResponses];

export type PinAnalysisApiAnalysesAnalysisIdPinPatchData = {
    /**
     * Body
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Analysis Id
         */
        analysis_id: number;
    };
    query?: never;
    url: '/api/analyses/{analysis_id}/pin';
};

export type PinAnalysisApiAnalysesAnalysisIdPinPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PinAnalysisApiAnalysesAnalysisIdPinPatchError = PinAnalysisApiAnalysesAnalysisIdPinPatchErrors[keyof PinAnalysisApiAnalysesAnalysisIdPinPatchErrors];

export type PinAnalysisApiAnalysesAnalysisIdPinPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ShareAnalysisApiAnalysesAnalysisIdSharePostData = {
    body: ShareAnalysisRequest;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: number;
    };
    query?: never;
    url: '/api/analyses/{analysis_id}/share';
};

export type ShareAnalysisApiAnalysesAnalysisIdSharePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ShareAnalysisApiAnalysesAnalysisIdSharePostError = ShareAnalysisApiAnalysesAnalysisIdSharePostErrors[keyof ShareAnalysisApiAnalysesAnalysisIdSharePostErrors];

export type ShareAnalysisApiAnalysesAnalysisIdSharePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UnshareAnalysisApiAnalysesAnalysisIdShareUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: number;
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/analyses/{analysis_id}/share/{user_id}';
};

export type UnshareAnalysisApiAnalysesAnalysisIdShareUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnshareAnalysisApiAnalysesAnalysisIdShareUserIdDeleteError = UnshareAnalysisApiAnalysesAnalysisIdShareUserIdDeleteErrors[keyof UnshareAnalysisApiAnalysesAnalysisIdShareUserIdDeleteErrors];

export type UnshareAnalysisApiAnalysesAnalysisIdShareUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetNewsApiNewsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Source
         */
        source?: string | null;
        /**
         * Force Refresh
         */
        force_refresh?: boolean;
    };
    url: '/api/news/';
};

export type GetNewsApiNewsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetNewsApiNewsGetError = GetNewsApiNewsGetErrors[keyof GetNewsApiNewsGetErrors];

export type GetNewsApiNewsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type NewsAiSummaryApiNewsAiSummaryPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/news/ai-summary';
};

export type NewsAiSummaryApiNewsAiSummaryPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type NewsAiReportApiNewsAiReportPostData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Question
         */
        question?: string;
    };
    url: '/api/news/ai-report';
};

export type NewsAiReportApiNewsAiReportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NewsAiReportApiNewsAiReportPostError = NewsAiReportApiNewsAiReportPostErrors[keyof NewsAiReportApiNewsAiReportPostErrors];

export type NewsAiReportApiNewsAiReportPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCalendarApiCalendarGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Force Refresh
         */
        force_refresh?: boolean;
        /**
         * Impact
         */
        impact?: string | null;
        /**
         * Country
         */
        country?: string | null;
    };
    url: '/api/calendar/';
};

export type GetCalendarApiCalendarGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCalendarApiCalendarGetError = GetCalendarApiCalendarGetErrors[keyof GetCalendarApiCalendarGetErrors];

export type GetCalendarApiCalendarGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListFavoritesApiBookmarksFavoritesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/bookmarks/favorites/';
};

export type ListFavoritesApiBookmarksFavoritesGetResponses = {
    /**
     * Response List Favorites Api Bookmarks Favorites  Get
     *
     * Successful Response
     */
    200: Array<FavoriteBookmarkResponse>;
};

export type ListFavoritesApiBookmarksFavoritesGetResponse = ListFavoritesApiBookmarksFavoritesGetResponses[keyof ListFavoritesApiBookmarksFavoritesGetResponses];

export type CreateFavoriteApiBookmarksFavoritesPostData = {
    body: FavoriteBookmarkCreate;
    path?: never;
    query?: never;
    url: '/api/bookmarks/favorites/';
};

export type CreateFavoriteApiBookmarksFavoritesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateFavoriteApiBookmarksFavoritesPostError = CreateFavoriteApiBookmarksFavoritesPostErrors[keyof CreateFavoriteApiBookmarksFavoritesPostErrors];

export type CreateFavoriteApiBookmarksFavoritesPostResponses = {
    /**
     * Successful Response
     */
    200: FavoriteBookmarkResponse;
};

export type CreateFavoriteApiBookmarksFavoritesPostResponse = CreateFavoriteApiBookmarksFavoritesPostResponses[keyof CreateFavoriteApiBookmarksFavoritesPostResponses];

export type DeleteFavoriteApiBookmarksFavoritesBmIdDeleteData = {
    body?: never;
    path: {
        /**
         * Bm Id
         */
        bm_id: number;
    };
    query?: never;
    url: '/api/bookmarks/favorites/{bm_id}';
};

export type DeleteFavoriteApiBookmarksFavoritesBmIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFavoriteApiBookmarksFavoritesBmIdDeleteError = DeleteFavoriteApiBookmarksFavoritesBmIdDeleteErrors[keyof DeleteFavoriteApiBookmarksFavoritesBmIdDeleteErrors];

export type DeleteFavoriteApiBookmarksFavoritesBmIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateFavoriteApiBookmarksFavoritesBmIdPutData = {
    body: FavoriteBookmarkUpdate;
    path: {
        /**
         * Bm Id
         */
        bm_id: number;
    };
    query?: never;
    url: '/api/bookmarks/favorites/{bm_id}';
};

export type UpdateFavoriteApiBookmarksFavoritesBmIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateFavoriteApiBookmarksFavoritesBmIdPutError = UpdateFavoriteApiBookmarksFavoritesBmIdPutErrors[keyof UpdateFavoriteApiBookmarksFavoritesBmIdPutErrors];

export type UpdateFavoriteApiBookmarksFavoritesBmIdPutResponses = {
    /**
     * Successful Response
     */
    200: FavoriteBookmarkResponse;
};

export type UpdateFavoriteApiBookmarksFavoritesBmIdPutResponse = UpdateFavoriteApiBookmarksFavoritesBmIdPutResponses[keyof UpdateFavoriteApiBookmarksFavoritesBmIdPutResponses];

export type ReorderFavoritesApiBookmarksFavoritesReorderPutData = {
    body: ReorderRequest;
    path?: never;
    query?: never;
    url: '/api/bookmarks/favorites/reorder/';
};

export type ReorderFavoritesApiBookmarksFavoritesReorderPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReorderFavoritesApiBookmarksFavoritesReorderPutError = ReorderFavoritesApiBookmarksFavoritesReorderPutErrors[keyof ReorderFavoritesApiBookmarksFavoritesReorderPutErrors];

export type ReorderFavoritesApiBookmarksFavoritesReorderPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListReadLaterApiBookmarksReadLaterGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/bookmarks/read-later/';
};

export type ListReadLaterApiBookmarksReadLaterGetResponses = {
    /**
     * Response List Read Later Api Bookmarks Read Later  Get
     *
     * Successful Response
     */
    200: Array<ReadLaterBookmarkResponse>;
};

export type ListReadLaterApiBookmarksReadLaterGetResponse = ListReadLaterApiBookmarksReadLaterGetResponses[keyof ListReadLaterApiBookmarksReadLaterGetResponses];

export type CreateReadLaterApiBookmarksReadLaterPostData = {
    body: ReadLaterBookmarkCreate;
    path?: never;
    query?: never;
    url: '/api/bookmarks/read-later/';
};

export type CreateReadLaterApiBookmarksReadLaterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateReadLaterApiBookmarksReadLaterPostError = CreateReadLaterApiBookmarksReadLaterPostErrors[keyof CreateReadLaterApiBookmarksReadLaterPostErrors];

export type CreateReadLaterApiBookmarksReadLaterPostResponses = {
    /**
     * Successful Response
     */
    200: ReadLaterBookmarkResponse;
};

export type CreateReadLaterApiBookmarksReadLaterPostResponse = CreateReadLaterApiBookmarksReadLaterPostResponses[keyof CreateReadLaterApiBookmarksReadLaterPostResponses];

export type UpdateReadLaterExpiryApiBookmarksReadLaterBmIdExpiryPatchData = {
    body: ReadLaterExpiryUpdate;
    path: {
        /**
         * Bm Id
         */
        bm_id: number;
    };
    query?: never;
    url: '/api/bookmarks/read-later/{bm_id}/expiry';
};

export type UpdateReadLaterExpiryApiBookmarksReadLaterBmIdExpiryPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateReadLaterExpiryApiBookmarksReadLaterBmIdExpiryPatchError = UpdateReadLaterExpiryApiBookmarksReadLaterBmIdExpiryPatchErrors[keyof UpdateReadLaterExpiryApiBookmarksReadLaterBmIdExpiryPatchErrors];

export type UpdateReadLaterExpiryApiBookmarksReadLaterBmIdExpiryPatchResponses = {
    /**
     * Successful Response
     */
    200: ReadLaterBookmarkResponse;
};

export type UpdateReadLaterExpiryApiBookmarksReadLaterBmIdExpiryPatchResponse = UpdateReadLaterExpiryApiBookmarksReadLaterBmIdExpiryPatchResponses[keyof UpdateReadLaterExpiryApiBookmarksReadLaterBmIdExpiryPatchResponses];

export type DeleteReadLaterApiBookmarksReadLaterBmIdDeleteData = {
    body?: never;
    path: {
        /**
         * Bm Id
         */
        bm_id: number;
    };
    query?: never;
    url: '/api/bookmarks/read-later/{bm_id}';
};

export type DeleteReadLaterApiBookmarksReadLaterBmIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteReadLaterApiBookmarksReadLaterBmIdDeleteError = DeleteReadLaterApiBookmarksReadLaterBmIdDeleteErrors[keyof DeleteReadLaterApiBookmarksReadLaterBmIdDeleteErrors];

export type DeleteReadLaterApiBookmarksReadLaterBmIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TogglePinReadLaterApiBookmarksReadLaterBmIdPinPatchData = {
    body?: never;
    path: {
        /**
         * Bm Id
         */
        bm_id: number;
    };
    query?: never;
    url: '/api/bookmarks/read-later/{bm_id}/pin';
};

export type TogglePinReadLaterApiBookmarksReadLaterBmIdPinPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TogglePinReadLaterApiBookmarksReadLaterBmIdPinPatchError = TogglePinReadLaterApiBookmarksReadLaterBmIdPinPatchErrors[keyof TogglePinReadLaterApiBookmarksReadLaterBmIdPinPatchErrors];

export type TogglePinReadLaterApiBookmarksReadLaterBmIdPinPatchResponses = {
    /**
     * Successful Response
     */
    200: ReadLaterBookmarkResponse;
};

export type TogglePinReadLaterApiBookmarksReadLaterBmIdPinPatchResponse = TogglePinReadLaterApiBookmarksReadLaterBmIdPinPatchResponses[keyof TogglePinReadLaterApiBookmarksReadLaterBmIdPinPatchResponses];

export type ReorderPinnedReadLaterApiBookmarksReadLaterReorderPutData = {
    body: ReadLaterReorderRequest;
    path?: never;
    query?: never;
    url: '/api/bookmarks/read-later/reorder/';
};

export type ReorderPinnedReadLaterApiBookmarksReadLaterReorderPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReorderPinnedReadLaterApiBookmarksReadLaterReorderPutError = ReorderPinnedReadLaterApiBookmarksReadLaterReorderPutErrors[keyof ReorderPinnedReadLaterApiBookmarksReadLaterReorderPutErrors];

export type ReorderPinnedReadLaterApiBookmarksReadLaterReorderPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
